#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# start-turn-native.sh — Run coturn NATIVELY on Linux (NO Docker required)
# GitHub: https://github.com/coturn/coturn
#
# Works on: Ubuntu 20.04+, Debian 11+, Raspberry Pi OS
# Installs coturn directly via apt — no Docker, no containers
#
# Usage:
#   chmod +x start-turn-native.sh
#   sudo ./start-turn-native.sh
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Must run as root ──────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  echo "[ERROR] This script must be run as root (use sudo):"
  echo "  sudo ./start-turn-native.sh"
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[TURN]${NC} $*"; }
success() { echo -e "${GREEN}[TURN]${NC} $*"; }
warn()    { echo -e "${YELLOW}[TURN]${NC} $*"; }
error()   { echo -e "${RED}[TURN]${NC} $*" >&2; }

echo ""
echo "  ╔══════════════════════════════════════════════════════╗"
echo "  ║  MeetSpace — Native coturn (No Docker) on Linux     ║"
echo "  ║  GitHub: github.com/coturn/coturn                   ║"
echo "  ╚══════════════════════════════════════════════════════╝"
echo ""

# ── Detect OS ─────────────────────────────────────────────────────────────────
if ! command -v apt &>/dev/null; then
  error "This script requires apt (Ubuntu/Debian). For other distros, see:"
  echo "  Fedora/RHEL: sudo dnf install coturn"
  echo "  Arch:        sudo pacman -S coturn"
  exit 1
fi

# ── Step 1: Install coturn ────────────────────────────────────────────────────
info "Step 1/5 — Installing coturn via apt..."
apt update -qq
apt install -y coturn

COTURN_VERSION=$(turnserver --version 2>&1 | head -1 || echo "unknown")
success "coturn installed: $COTURN_VERSION"

# ── Step 2: Detect local IP ───────────────────────────────────────────────────
info "Step 2/5 — Detecting local IP address..."

LOCAL_IP=""
# Method 1: ip route (most reliable)
if command -v ip &>/dev/null; then
  LOCAL_IP=$(ip route get 8.8.8.8 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1)}' | head -1 || true)
fi
# Method 2: hostname -I
if [[ -z "$LOCAL_IP" ]] && command -v hostname &>/dev/null; then
  LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || true)
fi
# Fallback
if [[ -z "$LOCAL_IP" ]]; then
  LOCAL_IP="127.0.0.1"
  warn "Could not detect IP — using 127.0.0.1"
fi

success "Local IP: $LOCAL_IP"

# ── Step 3: Write coturn config ───────────────────────────────────────────────
info "Step 3/5 — Writing coturn config to /etc/turnserver.conf..."

cat > /etc/turnserver.conf <<EOF
# ─────────────────────────────────────────────────────────────────────────────
# coturn config — Native install (no Docker)
# Generated by start-turn-native.sh
# GitHub: https://github.com/coturn/coturn
# ─────────────────────────────────────────────────────────────────────────────

# ── Network ───────────────────────────────────────────────────────────────────
external-ip=$LOCAL_IP
listening-ip=0.0.0.0
listening-port=3478
tls-listening-port=5349

# ── Relay Ports ───────────────────────────────────────────────────────────────
min-port=49152
max-port=65535

# ── Authentication ────────────────────────────────────────────────────────────
use-auth-secret
static-auth-secret=localdevelopmentsecret123
credential-lifetime=86400

# ── Realm ─────────────────────────────────────────────────────────────────────
realm=localhost

# ── Security ──────────────────────────────────────────────────────────────────
no-multicast-peers
no-cli
fingerprint

# ── Logging ───────────────────────────────────────────────────────────────────
verbose
log-file=/var/log/coturn.log
EOF

success "Config written to /etc/turnserver.conf"

# ── Step 4: Enable coturn service ─────────────────────────────────────────────
info "Step 4/5 — Enabling coturn systemd service..."

# Enable the service in /etc/default/coturn
if [[ -f /etc/default/coturn ]]; then
  # Uncomment TURNSERVER_ENABLED=1
  sed -i 's/^#\s*TURNSERVER_ENABLED=.*/TURNSERVER_ENABLED=1/' /etc/default/coturn
  # If line doesn't exist, add it
  if ! grep -q "TURNSERVER_ENABLED=1" /etc/default/coturn; then
    echo "TURNSERVER_ENABLED=1" >> /etc/default/coturn
  fi
  success "Enabled TURNSERVER_ENABLED=1 in /etc/default/coturn"
fi

# Reload systemd and restart coturn
systemctl daemon-reload
systemctl enable coturn
systemctl restart coturn

sleep 2

# ── Step 5: Verify ────────────────────────────────────────────────────────────
info "Step 5/5 — Verifying coturn is running..."

if systemctl is-active --quiet coturn; then
  echo ""
  echo "  ╔══════════════════════════════════════════════════════╗"
  echo "  ║   ✅  coturn TURN Server is RUNNING (native)!       ║"
  echo "  ╚══════════════════════════════════════════════════════╝"
  echo ""
  success "STUN/TURN address : ${GREEN}$LOCAL_IP:3478${NC}"
  success "Config file       : /etc/turnserver.conf"
  success "Log file          : /var/log/coturn.log"
  success "Service           : systemctl status coturn"
  echo ""
  echo "  ── Update your .env (on your dev machine): ─────────────"
  echo -e "  ${YELLOW}TURN_HOST=$LOCAL_IP${NC}"
  echo -e "  ${YELLOW}TURN_PORT=3478${NC}"
  echo -e "  ${YELLOW}TURN_SECRET=localdevelopmentsecret123${NC}"
  echo ""
  echo "  ── Useful commands: ────────────────────────────────────"
  echo "  sudo systemctl status coturn       # Check status"
  echo "  sudo systemctl restart coturn      # Restart"
  echo "  sudo systemctl stop coturn         # Stop"
  echo "  sudo journalctl -u coturn -f       # Live logs"
  echo "  sudo tail -f /var/log/coturn.log   # Log file"
  echo ""
  echo "  ── Test with Trickle ICE: ──────────────────────────────"
  echo "  https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/"
  echo "  URI: turn:$LOCAL_IP:3478"
  echo "  (Get username/password from: node 'TURN Server/test-credentials.js')"
  echo ""
  echo "  ── Live logs (Ctrl+C to exit — service keeps running): ─"
  echo ""
  journalctl -u coturn -f --no-pager
else
  error "coturn failed to start! Check logs:"
  journalctl -u coturn --no-pager -n 30
  echo ""
  error "Also check: /var/log/coturn.log"
  exit 1
fi
